// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kedomciogkekuqawboio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlZG9tY2lvZ2tla3VxYXdib2lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMDcwNjYsImV4cCI6MjA2Mzc4MzA2Nn0.YunmIRm6nUfMbAiBWWJEeeMDtDG44wZN7yqiqorLqvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);